/** CLI確認トークン（verify から import してもスクリプト本体は実行しない） */
export const FETCH_CANDIDATES_CONFIRM_TOKEN = 'FETCH_CANDIDATES';
export const IMPORT_APPROVED_CONFIRM_TOKEN = 'IMPORT_APPROVED';
export const FETCH_DAILY_30_CONFIRM_TOKEN = 'FETCH_DAILY_30';

export const FETCH_DAILY_30_PROMPT =
  '続行するには FETCH_DAILY_30 と入力してください。';

export const GENERATE_DAILY_30_COPY_CONFIRM_TOKEN = 'GENERATE_DAILY_30_COPY';

export const GENERATE_DAILY_30_COPY_PROMPT =
  '続行するには GENERATE_DAILY_30_COPY と入力してください。';

export const IMPORT_DAILY_30_DRAFT_CANDIDATES_CONFIRM_TOKEN =
  'IMPORT_DAILY_30_DRAFT_CANDIDATES';

export const IMPORT_DAILY_30_DRAFT_CANDIDATES_PROMPT =
  '続行するには IMPORT_DAILY_30_DRAFT_CANDIDATES と入力してください。';
